# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_delete_carousel'),
        ('cart', '0007_auto_20170301_1823'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set([('product', 'cart')]),
        ),
    ]
