# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20170207_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='adress',
        ),
    ]
