# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170106_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
