# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
