# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_detail'),
        ('catalog', '0007_delete_carousel'),
    ]

    operations = [
    ]
