# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 19:22
from __future__ import unicode_literals

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170105_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=apps.catalog.models.Product.get_image_path),
        ),
    ]
