# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-18 16:30
from __future__ import unicode_literals

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20170321_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=1, upload_to=apps.catalog.models.get_image_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default=1, upload_to=apps.catalog.models.get_image_path),
            preserve_default=False,
        ),
    ]
